//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionVirtual04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class area
    {
        public area()
        {
            this.contrato = new HashSet<contrato>();
        }
    
        public int aCodigo { get; set; }
        public string aDescripcion { get; set; }
    
        public virtual ICollection<contrato> contrato { get; set; }
    }
}
