//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionVirtual04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrato
    {
        public int cCodigo { get; set; }
        public Nullable<System.DateTime> cFecha { get; set; }
        public Nullable<System.DateTime> cFechaFin { get; set; }
        public Nullable<decimal> cSueldo { get; set; }
        public Nullable<int> aCodigo { get; set; }
        public Nullable<System.DateTime> cFechaInicio { get; set; }
        public Nullable<int> eCodigo { get; set; }
    
        public virtual area area { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
